- backend/buildeR.API/Startup.cs
- backend/buildeR.DAL/Context/ModelBuilderExtensions.cs
- backend/buildeR.DAL/Migrations/BuilderContextModelSnapshot.cs
After review I noticed that adding db context is incorrect and Idk why but id adding operation to user was missing in snapshot.
I already fix it and I will be more careful
> fixing bugs with database

- backend/buildeR.BLL/Services/SecretService.cs
From now, SecretService implement ISecretService explicity
> Fix a typo in secret serivce.

- backend/buildeR.API/Controllers/ProjectsController.cs
- backend/buildeR.API/Extensions/ServiceExtensions.cs
- backend/buildeR.BLL/Exceptions/ForbiddenExeption.cs
- backend/buildeR.BLL/Services/Abstract/BaseCrudService.cs
- backend/buildeR.BLL/Services/Abstract/IProjectService.cs
- backend/buildeR.BLL/Services/ProjectService.cs
add methods(Get/Post/Put) to project controller and project service
> Feature/project detailst component(backend)

- frontend/src/app/core/services/project.service.ts
- frontend/src/app/modules/project/project-create/project-create.component.html
- frontend/src/app/modules/project/project-create/project-create.component.sass
- frontend/src/app/modules/project/project-create/project-create.component.spec.ts
- frontend/src/app/modules/project/project-create/project-create.component.ts
- frontend/src/app/modules/project/project-routing.module.ts
- frontend/src/app/modules/project/project-settings/project-settings.component.html
- frontend/src/app/modules/project/project-settings/project-settings.component.sass
- frontend/src/app/modules/project/project-settings/project-settings.component.spec.ts
- frontend/src/app/modules/project/project-settings/project-settings.component.ts
- frontend/src/app/modules/project/project.component.html
- frontend/src/app/modules/project/project.component.sass
- frontend/src/app/modules/project/project.component.spec.ts
- frontend/src/app/modules/project/project.component.ts
- frontend/src/app/modules/project/project.module.ts
- frontend/src/app/modules/work-space/dashboard/dashboard.component.html
- frontend/src/app/modules/work-space/dashboard/dashboard.component.ts
- frontend/src/app/modules/work-space/work-space-routing.module.ts
- frontend/src/app/shared/models/project/new-project.ts
- frontend/src/app/shared/models/project/project-settings.ts
- frontend/src/app/shared/models/project/project.ts
- frontend/src/app/shared/shared.module.ts
project (project-routing.module, project.module, project.component, project-setting.component, project-create.component)
> Feature/project detailst component(frontend)

- backend/buildeR.BLL/Services/ProjectService.cs
Throw exception in GetExecutiveBuild(projectId) when project does not exist
> Change GetExecutiveBuild(projectId)

- frontend/src/app/core/services/project.service.ts
- frontend/src/app/core/services/user-settings.service.ts
- frontend/src/app/core/services/user.service.ts
- frontend/src/environments/environment.ts
Fix bug in frontend application with WebAPI endpoint (endpoint was differ in development and poduction mode)
> Fix bug with api/ endpoint

- backend/buildeR.API/Startup.cs
I noticed that my conflict solution in Startup was unsuccessful and it deleted several lines that were before, so I added them again
> fix bug with Startup conflict

- backend/buildeR.API/Startup.cs
- backend/buildeR.API/buildeR.API.csproj
- backend/buildeR.Common/buildeR.Common.csproj
Go to **localhost:5050/swagger** to see API definition
Also configured swagger to show Fluent Validation rules in schemas.
Example - _UserDto_:
```C#
RuleFor(u => u.LastName).MaximumLength(35).NotEmpty();
RuleFor(u => u.FirstName).MaximumLength(30).NotNull();
```
results in
> Added swagger

- frontend/src/app/modules/project/project.component.html
- frontend/src/app/modules/project/project.component.ts
- frontend/src/app/shared/components/not-found/not-found.component.html
- frontend/src/app/shared/shared.module.ts
Fix tabs selection in project component
> Fix tabs selection

- backend/buildeR.API/Extensions/ServiceExtensions.cs
- backend/buildeR.API/appsettings.json
- backend/buildeR.Processor/Extensions/ServiceExtensions.cs
- backend/buildeR.Processor/Startup.cs
- backend/buildeR.RabbitMQ/Models/ConnectionFactorySettings.cs
- backend/buildeR.RabbitMQ/Realization/OwnConnectionFactory.cs
- backend/buildeR.RabbitMQ/buildeR.RabbitMq.csproj
appsettings now looks like this:
```
...
"RabbitMQ": {
"ConnectionSettings": {
"RABBIT_MQ_HOST_NAME": "localhost",
"RABBIT_MQ_USERNAME": "guest",
"RABBIT_MQ_PASSWORD": "guest"
},
"Queues": {
"ToProcessor": {
"ExchangeName": "buildProcessorExchanger",
"ExchangeType": "direct",
"QueueName": "buildProcessorQueue",
"RoutingKey": "launchBuildKey"
}
}
}
...
```
> RabbitMQ environment variables

- frontend/src/app/core/components/registration-dialog/registration-dialog.component.html
- frontend/src/app/core/components/registration-dialog/registration-dialog.component.sass
- frontend/src/app/modules/project/project-create/project-create.component.html
- frontend/src/app/modules/project/project-create/project-create.component.sass
add stars for the required fields in create projects page and in sign up modal
> add stars for the required fields

- frontend/src/app/modules/work-space/dashboard/dashboard.component.html
I made a mistake in resolving my last conflict
> Fix router links in the dashboard

- backend/buildeR.BLL/Services/GithubClient.cs
- backend/buildeR.BLL/Services/SynchronizationService.cs
- backend/buildeR.Common/DTO/Synchronization/Github/GithubRepository.cs
- backend/buildeR.Common/DTO/Synchronization/Repository.cs
- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/core/models/Repository.ts
- frontend/src/app/modules/project/project-create/project-create.component.html
- frontend/src/app/modules/project/project-create/project-create.component.sass
- frontend/src/app/modules/project/project.module.ts
- Add ability to load more than 100 user repos
- Add ability to filter repository list by name
> Github synchronization enhancement 

- backend/buildeR.Common/Enums/NotificationType.cs
> change enum

- frontend/src/app/modules/project/project-create/project-create.component.html
- frontend/src/app/modules/project/project-create/project-create.component.ts
- frontend/src/app/modules/project/project.module.ts
Change ng-select component to NbgTypehead component in project-create component
> Change ng-select component to NbgTypehead component

- frontend/src/app/modules/work-space/dashboard/dashboard.component.html
My IDE added redundant spaces what led to the broken routes
> Remove redundant spaces

- frontend/src/app/modules/work-space/notifications-block/notifications-block.component.sass
fixed (The modal with notifications doesn't close when opening the dropdown user's profile menu)
> Added z-index 9999 for notifications-background

- frontend/src/app/modules/project/logging-terminal/logging-terminal.component.html
- frontend/src/app/modules/project/logging-terminal/logging-terminal.component.sass
- frontend/src/app/modules/project/logging-terminal/logging-terminal.component.ts
> Added autoscrolling and word wrapping to the terminal

- backend/buildeR.API/Controllers/SynchronizationController.cs
- backend/buildeR.BLL/Interfaces/IGithubClient.cs
- backend/buildeR.BLL/Interfaces/ISynchronizationService.cs
- backend/buildeR.BLL/Services/GithubClient.cs
- backend/buildeR.BLL/Services/SynchronizationHelper.cs
- backend/buildeR.BLL/Services/SynchronizationService.cs
- backend/buildeR.Common/DTO/Synchronization/RepositoryLinkDTO.cs
- frontend/src/app/core/services/synchronization.service.ts
- frontend/src/app/core/validators/repo-url.async-validator.ts
- frontend/src/app/modules/project/project-create/project-create.component.html
- frontend/src/app/modules/project/project-create/project-create.component.ts
From now it is not possible to create repository with link to unexisting or private repository
> Add async validator for repository url

- backend/buildeR.BLL/MappingProfiles/ProjectProfile.cs
- backend/buildeR.BLL/Services/ProjectService.cs
- backend/buildeR.BLL/Services/SynchronizationService.cs
- backend/buildeR.Common/DTO/Project/NewProjectDTO.cs
- backend/buildeR.Common/DTO/Project/ProjectDTO.cs
- backend/buildeR.DAL/Context/ModelBuilderExtensions.cs
- backend/buildeR.DAL/Entities/Project.cs
- backend/buildeR.DAL/Migrations/20200826075948_RemoveRepositoryNameFieldFromProjectEntity.Designer.cs
- backend/buildeR.DAL/Migrations/20200826075948_RemoveRepositoryNameFieldFromProjectEntity.cs
- frontend/src/app/modules/project/project-create/project-create.component.html
- frontend/src/app/modules/project/project-create/project-create.component.ts
- frontend/src/app/shared/models/project/new-project.ts
- frontend/src/app/shared/models/project/project.ts
I have removed Repository field from Project entity because of this field is duplicate from _Repository.Name field
> Remove unnecessary field from project entity (and related to it DTOs)

- frontend/src/app/modules/user/notification-setting/notification-setting.component.ts
Fixed receive updates items at Notification settings tab disappear after saving
> added (mapping description) during result from saving

- backend/buildeR.BLL/Services/UserService.cs
- frontend/src/app/core/services/authentication.service.ts
- frontend/src/app/core/services/firebase-sign-in.service.ts
- frontend/src/app/modules/user/user-settings/user-settings.component.ts
- frontend/src/app/shared/models/user/user.ts
fix updating user in user settings
fix setting new firebase user after linking providers
fix linking buttons checks
> fix updating user in user settings

- backend/buildeR.BLL/Services/SynchronizationService.cs
- frontend/src/app/modules/user/credential-settings/credential-settings.component.html
- frontend/src/app/modules/user/credential-settings/credential-settings.component.sass
- Fix repository url validation
- Change access token submit button
- Add divider to access token form
- Access token tutorial link is external from now
> Github synchronization enhancment

- frontend/src/app/modules/project/project-triggers/project-triggers.component.ts
Hotfix "Run on schedule switcher at the Project settings tab is not clickable"
> Changed id for label

- backend/buildeR.BLL/Services/BuildService.cs
- backend/buildeR.BLL/Services/NotificationsService.cs
- backend/buildeR.Common/DTO/Notification/NewNotificationDTO.cs
- backend/buildeR.Common/DTO/Notification/NotificationDTO.cs
- backend/buildeR.DAL/Entities/Notification.cs
- backend/buildeR.DAL/Migrations/20200903223026_notificationsItemId.Designer.cs
- backend/buildeR.DAL/Migrations/20200903223026_notificationsItemId.cs
- frontend/src/app/core/services/signalr-hub-factory.service.ts
- frontend/src/app/modules/work-space/notifications-block/notifications-block.component.html
- frontend/src/app/modules/work-space/notifications-block/notifications-block.component.ts
- frontend/src/app/shared/models/notification.ts
Now click on notification navigates to the item's details page(works only for build history for now)
Example:
> Added interactivity to notifications

- frontend/src/app/modules/work-space/dashboard/dashboard.component.sass
- frontend/src/app/shared/components/projects-display/projects-display.component.html
> Added  border-bottom and disable text-decoration

- frontend/src/app/core/services/build-history.service.ts
- frontend/src/app/modules/project/project-build-history/project-build-history.component.ts
- frontend/src/app/modules/project/project.component.ts
When user triggers build from a project page build history refreshes
> Added refresh build histories on the build trigger

- backend/buildeR.Processor/Services/ProcessorService.cs
There are now different statuses for successful and failed builds. There is also "Error" status for fail of our system, but I couldn't recreate such behavior to test it.
> Return failure for failed builds

- backend/buildeR.API/appsettings.json
Somebody deleted chat exchange configuration from appsettings. Maybe it happens in time of merge
> fixed chat

- backend/buildeR.BLL/Services/WebhooksHandler.cs
- backend/buildeR.Common/Enums/RemoteTriggerType.cs
There was a bug when both event are choosed: noone of them was handled when github fire thay
> Fix bug with github webhooks handling

- frontend/src/app/modules/group/group-list/group-list.component.html
- frontend/src/app/modules/group/group-list/group-list.component.sass
- frontend/src/app/modules/group/group-list/group-list.component.ts
- frontend/src/app/modules/group/group-settings/group-settings.component.html
- frontend/src/app/modules/group/group-settings/group-settings.component.ts
- frontend/src/app/modules/group/group/group.component.html
- frontend/src/app/modules/group/group/group.component.ts
now only owner and admin can delete project and see setting
> fix group permissions and grop list page

- frontend/src/app/modules/project/project-build-history/project-build-history.component.sass
> some fix to build history page style

- frontend/src/app/modules/landing-page/landing-page.component.html
now when clicking on item or somewhere below header, dropdown menu is collapsing
> add dropdown menu collapse landing page

- backend/buildeR.BLL/Services/UserService.cs
- frontend/src/app/core/services/firebase-sign-in.service.ts
add 404 when user not found login
> fix login/register
